# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1095, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.body = QtWidgets.QWidget(self.centralwidget)
        self.body.setObjectName("body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navigator = QtWidgets.QWidget(self.body)
        self.navigator.setObjectName("navigator")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.navigator)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.navigator)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.navigator)
        self.verticalLayout_2.addWidget(self.body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1095, 24))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDepartment = QtWidgets.QAction(MainWindow)
        self.actionDepartment.setObjectName("actionDepartment")
        self.on = QtWidgets.QAction(MainWindow)
        self.on.setObjectName("on")
        self.actionDepartment_2 = QtWidgets.QAction(MainWindow)
        self.actionDepartment_2.setObjectName("actionDepartment_2")
        self.actionDepartments = QtWidgets.QAction(MainWindow)
        self.actionDepartments.setObjectName("actionDepartments")
        self.actionStates = QtWidgets.QAction(MainWindow)
        self.actionStates.setObjectName("actionStates")
        self.actionZones = QtWidgets.QAction(MainWindow)
        self.actionZones.setObjectName("actionZones")
        self.actionProduct_Groups = QtWidgets.QAction(MainWindow)
        self.actionProduct_Groups.setObjectName("actionProduct_Groups")
        self.actionSuppliers = QtWidgets.QAction(MainWindow)
        self.actionSuppliers.setObjectName("actionSuppliers")
        self.actionMarital_Status = QtWidgets.QAction(MainWindow)
        self.actionMarital_Status.setObjectName("actionMarital_Status")
        self.menuMenu.addAction(self.actionDepartments)
        self.menuMenu.addAction(self.actionMarital_Status)
        self.menuMenu.addAction(self.actionProduct_Groups)
        self.menuMenu.addAction(self.actionStates)
        self.menuMenu.addAction(self.actionSuppliers)
        self.menuMenu.addAction(self.actionZones)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome, please use the Menu in the upper left corner to browse this app!!"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionDepartment.setText(_translate("MainWindow", "Department"))
        self.on.setText(_translate("MainWindow", "Department"))
        self.actionDepartment_2.setText(_translate("MainWindow", "Department"))
        self.actionDepartments.setText(_translate("MainWindow", "Departments"))
        self.actionStates.setText(_translate("MainWindow", "States"))
        self.actionZones.setText(_translate("MainWindow", "Zones"))
        self.actionProduct_Groups.setText(_translate("MainWindow", "Product Groups"))
        self.actionSuppliers.setText(_translate("MainWindow", "Suppliers"))
        self.actionMarital_Status.setText(_translate("MainWindow", "Marital Status"))
