# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/maritalStatus.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_maritalStatus(object):
    def setupUi(self, maritalStatus):
        maritalStatus.setObjectName("maritalStatus")
        maritalStatus.resize(638, 562)
        self.verticalLayout = QtWidgets.QVBoxLayout(maritalStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_add = QtWidgets.QWidget(maritalStatus)
        self.panel_add.setMinimumSize(QtCore.QSize(0, 120))
        self.panel_add.setMaximumSize(QtCore.QSize(16777215, 120))
        self.panel_add.setObjectName("panel_add")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.panel_add)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title_maritalstatus = QtWidgets.QLabel(self.panel_add)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_maritalstatus.setFont(font)
        self.title_maritalstatus.setObjectName("title_maritalstatus")
        self.verticalLayout_6.addWidget(self.title_maritalstatus)
        self.label_name_maritalstatus = QtWidgets.QLabel(self.panel_add)
        self.label_name_maritalstatus.setObjectName("label_name_maritalstatus")
        self.verticalLayout_6.addWidget(self.label_name_maritalstatus)
        self.name_maritalstatus = QtWidgets.QLineEdit(self.panel_add)
        self.name_maritalstatus.setObjectName("name_maritalstatus")
        self.verticalLayout_6.addWidget(self.name_maritalstatus)
        self.on_add_maritalstatus = QtWidgets.QPushButton(self.panel_add)
        self.on_add_maritalstatus.setObjectName("on_add_maritalstatus")
        self.verticalLayout_6.addWidget(self.on_add_maritalstatus)
        self.verticalLayout.addWidget(self.panel_add)
        self.panel_list = QtWidgets.QWidget(maritalStatus)
        self.panel_list.setObjectName("panel_list")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.panel_list)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_maritalstatus = QtWidgets.QTableWidget(self.panel_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_maritalstatus.sizePolicy().hasHeightForWidth())
        self.list_maritalstatus.setSizePolicy(sizePolicy)
        self.list_maritalstatus.setMinimumSize(QtCore.QSize(0, 400))
        self.list_maritalstatus.setObjectName("list_maritalstatus")
        self.list_maritalstatus.setColumnCount(7)
        self.list_maritalstatus.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_maritalstatus.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_maritalstatus.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_maritalstatus.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_maritalstatus.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_maritalstatus.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_maritalstatus.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_maritalstatus.setHorizontalHeaderItem(6, item)
        self.verticalLayout_4.addWidget(self.list_maritalstatus)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout.addWidget(self.panel_list)

        self.retranslateUi(maritalStatus)
        QtCore.QMetaObject.connectSlotsByName(maritalStatus)

    def retranslateUi(self, maritalStatus):
        _translate = QtCore.QCoreApplication.translate
        maritalStatus.setWindowTitle(_translate("maritalStatus", "Form"))
        self.title_maritalstatus.setText(_translate("maritalStatus", "Marital Status List"))
        self.label_name_maritalstatus.setText(_translate("maritalStatus", "Name:"))
        self.on_add_maritalstatus.setText(_translate("maritalStatus", "Add"))
        item = self.list_maritalstatus.horizontalHeaderItem(0)
        item.setText(_translate("maritalStatus", "Id"))
        item = self.list_maritalstatus.horizontalHeaderItem(1)
        item.setText(_translate("maritalStatus", "Name"))
        item = self.list_maritalstatus.horizontalHeaderItem(2)
        item.setText(_translate("maritalStatus", "Created"))
        item = self.list_maritalstatus.horizontalHeaderItem(3)
        item.setText(_translate("maritalStatus", "Updated"))
        item = self.list_maritalstatus.horizontalHeaderItem(4)
        item.setText(_translate("maritalStatus", "Active"))
