# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/productGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_productGroup(object):
    def setupUi(self, productGroup):
        productGroup.setObjectName("productGroup")
        productGroup.resize(655, 368)
        self.verticalLayout = QtWidgets.QVBoxLayout(productGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_add = QtWidgets.QWidget(productGroup)
        self.panel_add.setMinimumSize(QtCore.QSize(0, 120))
        self.panel_add.setMaximumSize(QtCore.QSize(16777215, 120))
        self.panel_add.setObjectName("panel_add")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.panel_add)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title_productGroup = QtWidgets.QLabel(self.panel_add)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_productGroup.setFont(font)
        self.title_productGroup.setObjectName("title_productGroup")
        self.verticalLayout_6.addWidget(self.title_productGroup)
        self.label_name_productGroup = QtWidgets.QLabel(self.panel_add)
        self.label_name_productGroup.setObjectName("label_name_productGroup")
        self.verticalLayout_6.addWidget(self.label_name_productGroup)
        self.name_productGroup = QtWidgets.QLineEdit(self.panel_add)
        self.name_productGroup.setObjectName("name_productGroup")
        self.verticalLayout_6.addWidget(self.name_productGroup)
        self.on_add_productGroup = QtWidgets.QPushButton(self.panel_add)
        self.on_add_productGroup.setObjectName("on_add_productGroup")
        self.verticalLayout_6.addWidget(self.on_add_productGroup)
        self.verticalLayout.addWidget(self.panel_add)
        self.panel_list = QtWidgets.QWidget(productGroup)
        self.panel_list.setObjectName("panel_list")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.panel_list)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_productGroups = QtWidgets.QTableWidget(self.panel_list)
        self.list_productGroups.setMinimumSize(QtCore.QSize(0, 200))
        self.list_productGroups.setMaximumSize(QtCore.QSize(16777215, 200))
        self.list_productGroups.setObjectName("list_productGroups")
        self.list_productGroups.setColumnCount(6)
        self.list_productGroups.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_productGroups.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_productGroups.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_productGroups.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_productGroups.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_productGroups.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_productGroups.setHorizontalHeaderItem(5, item)
        self.list_productGroups.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.list_productGroups)
        self.verticalLayout.addWidget(self.panel_list)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(productGroup)
        QtCore.QMetaObject.connectSlotsByName(productGroup)

    def retranslateUi(self, productGroup):
        _translate = QtCore.QCoreApplication.translate
        productGroup.setWindowTitle(_translate("productGroup", "Form"))
        self.title_productGroup.setText(_translate("productGroup", "PRODUCT GROUP LIST"))
        self.label_name_productGroup.setText(_translate("productGroup", "Name:"))
        self.on_add_productGroup.setText(_translate("productGroup", "Add"))
        item = self.list_productGroups.horizontalHeaderItem(0)
        item.setText(_translate("productGroup", "Id"))
        item = self.list_productGroups.horizontalHeaderItem(1)
        item.setText(_translate("productGroup", "Name"))
        item = self.list_productGroups.horizontalHeaderItem(2)
        item.setText(_translate("productGroup", "Commission"))
        item = self.list_productGroups.horizontalHeaderItem(3)
        item.setText(_translate("productGroup", "Gain"))
        item = self.list_productGroups.horizontalHeaderItem(4)
        item.setText(_translate("productGroup", "Created"))
        item = self.list_productGroups.horizontalHeaderItem(5)
        item.setText(_translate("productGroup", "Updated"))
