# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/state.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_states(object):
    def setupUi(self, states):
        states.setObjectName("states")
        states.resize(689, 368)
        self.verticalLayout = QtWidgets.QVBoxLayout(states)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_add = QtWidgets.QWidget(states)
        self.panel_add.setMinimumSize(QtCore.QSize(0, 120))
        self.panel_add.setMaximumSize(QtCore.QSize(16777215, 120))
        self.panel_add.setObjectName("panel_add")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.panel_add)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title_state = QtWidgets.QLabel(self.panel_add)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_state.setFont(font)
        self.title_state.setObjectName("title_state")
        self.verticalLayout_6.addWidget(self.title_state)
        self.label_name_state = QtWidgets.QLabel(self.panel_add)
        self.label_name_state.setObjectName("label_name_state")
        self.verticalLayout_6.addWidget(self.label_name_state)
        self.name_state = QtWidgets.QLineEdit(self.panel_add)
        self.name_state.setObjectName("name_state")
        self.verticalLayout_6.addWidget(self.name_state)
        self.on_search_state = QtWidgets.QPushButton(self.panel_add)
        self.on_search_state.setObjectName("on_search_state")
        self.verticalLayout_6.addWidget(self.on_search_state)
        self.verticalLayout.addWidget(self.panel_add)
        self.panel_list = QtWidgets.QWidget(states)
        self.panel_list.setObjectName("panel_list")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.panel_list)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_states = QtWidgets.QTableWidget(self.panel_list)
        self.list_states.setMinimumSize(QtCore.QSize(0, 200))
        self.list_states.setMaximumSize(QtCore.QSize(16777215, 200))
        self.list_states.setObjectName("list_states")
        self.list_states.setColumnCount(5)
        self.list_states.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_states.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_states.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_states.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_states.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_states.setHorizontalHeaderItem(4, item)
        self.list_states.horizontalHeader().setCascadingSectionResizes(True)
        self.list_states.horizontalHeader().setDefaultSectionSize(123)
        self.list_states.horizontalHeader().setSortIndicatorShown(False)
        self.list_states.horizontalHeader().setStretchLastSection(True)
        self.list_states.verticalHeader().setDefaultSectionSize(30)
        self.list_states.verticalHeader().setSortIndicatorShown(False)
        self.list_states.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.list_states)
        self.verticalLayout.addWidget(self.panel_list)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(states)
        QtCore.QMetaObject.connectSlotsByName(states)

    def retranslateUi(self, states):
        _translate = QtCore.QCoreApplication.translate
        states.setWindowTitle(_translate("states", "Form"))
        self.title_state.setText(_translate("states", "STATES LIST"))
        self.label_name_state.setText(_translate("states", "Name:"))
        self.on_search_state.setText(_translate("states", "Add"))
        item = self.list_states.horizontalHeaderItem(0)
        item.setText(_translate("states", "Id"))
        item = self.list_states.horizontalHeaderItem(1)
        item.setText(_translate("states", "Name"))
        item = self.list_states.horizontalHeaderItem(2)
        item.setText(_translate("states", "Abreviation"))
        item = self.list_states.horizontalHeaderItem(3)
        item.setText(_translate("states", "Created"))
        item = self.list_states.horizontalHeaderItem(4)
        item.setText(_translate("states", "Updated"))
