# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/zone.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_zones(object):
    def setupUi(self, zones):
        zones.setObjectName("zones")
        zones.resize(629, 368)
        self.verticalLayout = QtWidgets.QVBoxLayout(zones)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_add = QtWidgets.QWidget(zones)
        self.panel_add.setMinimumSize(QtCore.QSize(0, 120))
        self.panel_add.setMaximumSize(QtCore.QSize(16777215, 120))
        self.panel_add.setObjectName("panel_add")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.panel_add)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title_zone = QtWidgets.QLabel(self.panel_add)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_zone.setFont(font)
        self.title_zone.setObjectName("title_zone")
        self.verticalLayout_6.addWidget(self.title_zone)
        self.label_name_zone = QtWidgets.QLabel(self.panel_add)
        self.label_name_zone.setObjectName("label_name_zone")
        self.verticalLayout_6.addWidget(self.label_name_zone)
        self.name_zone = QtWidgets.QLineEdit(self.panel_add)
        self.name_zone.setObjectName("name_zone")
        self.verticalLayout_6.addWidget(self.name_zone)
        self.on_add_zone = QtWidgets.QPushButton(self.panel_add)
        self.on_add_zone.setObjectName("on_add_zone")
        self.verticalLayout_6.addWidget(self.on_add_zone)
        self.verticalLayout.addWidget(self.panel_add)
        self.panel_list = QtWidgets.QWidget(zones)
        self.panel_list.setObjectName("panel_list")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.panel_list)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_zones = QtWidgets.QTableWidget(self.panel_list)
        self.list_zones.setMinimumSize(QtCore.QSize(0, 200))
        self.list_zones.setMaximumSize(QtCore.QSize(16777215, 200))
        self.list_zones.setObjectName("list_zones")
        self.list_zones.setColumnCount(7)
        self.list_zones.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_zones.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_zones.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_zones.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_zones.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_zones.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_zones.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.list_zones.setHorizontalHeaderItem(6, item)
        self.verticalLayout_4.addWidget(self.list_zones)
        self.verticalLayout.addWidget(self.panel_list)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(zones)
        QtCore.QMetaObject.connectSlotsByName(zones)

    def retranslateUi(self, zones):
        _translate = QtCore.QCoreApplication.translate
        zones.setWindowTitle(_translate("zones", "Form"))
        self.title_zone.setText(_translate("zones", "ZONE LIST"))
        self.label_name_zone.setText(_translate("zones", "Name:"))
        self.on_add_zone.setText(_translate("zones", "Add"))
        item = self.list_zones.horizontalHeaderItem(0)
        item.setText(_translate("zones", "Id"))
        item = self.list_zones.horizontalHeaderItem(1)
        item.setText(_translate("zones", "Name"))
        item = self.list_zones.horizontalHeaderItem(2)
        item.setText(_translate("zones", "Created"))
        item = self.list_zones.horizontalHeaderItem(3)
        item.setText(_translate("zones", "Updated"))
        item = self.list_zones.horizontalHeaderItem(4)
        item.setText(_translate("zones", "Active"))
