# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/update_supplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_supplier(object):
    def setupUi(self, update_supplier):
        update_supplier.setObjectName("update_supplier")
        update_supplier.resize(586, 145)
        self.verticalLayout = QtWidgets.QVBoxLayout(update_supplier)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confirms = QtWidgets.QWidget(update_supplier)
        self.confirms.setObjectName("confirms")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.confirms)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputs = QtWidgets.QWidget(self.confirms)
        self.inputs.setObjectName("inputs")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.inputs)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.inputs)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.update_name = QtWidgets.QLineEdit(self.inputs)
        self.update_name.setEnabled(True)
        self.update_name.setText("")
        self.update_name.setObjectName("update_name")
        self.horizontalLayout_2.addWidget(self.update_name)
        self.label_2 = QtWidgets.QLabel(self.inputs)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.update_document = QtWidgets.QLineEdit(self.inputs)
        self.update_document.setText("")
        self.update_document.setObjectName("update_document")
        self.horizontalLayout_2.addWidget(self.update_document)
        self.verticalLayout_2.addWidget(self.inputs)
        self.confirm_update = QtWidgets.QPushButton(self.confirms)
        self.confirm_update.setObjectName("confirm_update")
        self.verticalLayout_2.addWidget(self.confirm_update)
        self.verticalLayout.addWidget(self.confirms)

        self.retranslateUi(update_supplier)
        QtCore.QMetaObject.connectSlotsByName(update_supplier)

    def retranslateUi(self, update_supplier):
        _translate = QtCore.QCoreApplication.translate
        update_supplier.setWindowTitle(_translate("update_supplier", "Dialog"))
        self.label.setText(_translate("update_supplier", "Name: "))
        self.label_2.setText(_translate("update_supplier", "Document: "))
        self.confirm_update.setText(_translate("update_supplier", "Confirm"))
