# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/update_department.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(302, 114)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputs = QtWidgets.QWidget(Dialog)
        self.inputs.setObjectName("inputs")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.inputs)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.inputs)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.update_name = QtWidgets.QLineEdit(self.inputs)
        self.update_name.setObjectName("update_name")
        self.horizontalLayout.addWidget(self.update_name)
        self.verticalLayout.addWidget(self.inputs)
        self.confirms = QtWidgets.QWidget(Dialog)
        self.confirms.setObjectName("confirms")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.confirms)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.confirm_update = QtWidgets.QPushButton(self.confirms)
        self.confirm_update.setObjectName("confirm_update")
        self.verticalLayout_2.addWidget(self.confirm_update)
        self.verticalLayout.addWidget(self.confirms)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name: "))
        self.confirm_update.setText(_translate("Dialog", "Confirm"))
