# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/update_state.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update_state(object):
    def setupUi(self, update_state):
        update_state.setObjectName("update_state")
        update_state.resize(419, 114)
        self.verticalLayout = QtWidgets.QVBoxLayout(update_state)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confirms = QtWidgets.QWidget(update_state)
        self.confirms.setObjectName("confirms")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.confirms)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputs = QtWidgets.QWidget(self.confirms)
        self.inputs.setObjectName("inputs")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.inputs)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.inputs)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.update_name = QtWidgets.QLineEdit(self.inputs)
        self.update_name.setEnabled(True)
        self.update_name.setText("")
        self.update_name.setObjectName("update_name")
        self.horizontalLayout_2.addWidget(self.update_name)
        self.label_2 = QtWidgets.QLabel(self.inputs)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.update_abbreviation = QtWidgets.QLineEdit(self.inputs)
        self.update_abbreviation.setMaximumSize(QtCore.QSize(50, 16777215))
        self.update_abbreviation.setText("")
        self.update_abbreviation.setObjectName("update_abbreviation")
        self.horizontalLayout_2.addWidget(self.update_abbreviation)
        self.verticalLayout_2.addWidget(self.inputs)
        self.confirm_update = QtWidgets.QPushButton(self.confirms)
        self.confirm_update.setObjectName("confirm_update")
        self.verticalLayout_2.addWidget(self.confirm_update)
        self.verticalLayout.addWidget(self.confirms)

        self.retranslateUi(update_state)
        QtCore.QMetaObject.connectSlotsByName(update_state)

    def retranslateUi(self, update_state):
        _translate = QtCore.QCoreApplication.translate
        update_state.setWindowTitle(_translate("update_state", "Dialog"))
        self.label.setText(_translate("update_state", "Name: "))
        self.label_2.setText(_translate("update_state", "Abbreviation: "))
        self.confirm_update.setText(_translate("update_state", "Confirm"))
